version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build: ./server
    container_name: server
    ports:
      - "5001:5000"  # Host:Container port mapping
    environment:
      - PORT=5000    # Internal container port
      - ALLOWED_ORIGIN=http://localhost:5173  # Changed to localhost for client access
      - MONGODB_URI=mongodb://root:example@mongo:27017/crm-mini?authSource=admin
      - JWT_SECRET=my_jwt_secret_key
    depends_on:
      - mongo
    restart: unless-stopped

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:5001  # Must match server's host port (5001)
      - VITE_CURRENT_USER_KEY=MINI_CRM_LOGGED_IN_USER
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data: